### ISSUE TITLE
The type or namespace name 'Hero' could not be found

### ISSUE THREAD

**Issue by rocket5** [adammyhre/Unity-Inventory-System#3]
Looks like this was introduced in the Video 3 commit. Missing Hero class?

`Assets/_Project/Scripts/Persistence/SaveLoadSystem.cs(43,18): error CS0246: The type or namespace name 'Hero' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by adammyhre** [comment]
This is the same as Issue #2
